export const credentialRegistryAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "error", name: "AdminUnchanged", inputs: [] },
  {
    type: "error",
    name: "CredentialAlreadyRevoked",
    inputs: [{ name: "credentialId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CredentialNotFound",
    inputs: [{ name: "credentialId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "DuplicateActiveCredential",
    inputs: [
      { name: "student", type: "address", internalType: "address" },
      { name: "documentHash", type: "bytes32", internalType: "bytes32" },
    ],
  },
  { type: "error", name: "InvalidDocumentHash", inputs: [] },
  {
    type: "error",
    name: "IssuerAlreadyAuthorized",
    inputs: [{ name: "issuer", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "IssuerNotAuthorized",
    inputs: [{ name: "issuer", type: "address", internalType: "address" }],
  },
  { type: "error", name: "UnauthorizedAdmin", inputs: [] },
  { type: "error", name: "UnauthorizedIssuer", inputs: [] },
  { type: "error", name: "UnauthorizedRevoker", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  {
    type: "event",
    name: "AdminTransferred",
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousAdmin", type: "address", internalType: "address" },
      { indexed: true, name: "newAdmin", type: "address", internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "CredentialIssued",
    anonymous: false,
    inputs: [
      { indexed: true, name: "credentialId", type: "uint256", internalType: "uint256" },
      { indexed: true, name: "student", type: "address", internalType: "address" },
      { indexed: true, name: "issuer", type: "address", internalType: "address" },
      { indexed: false, name: "documentHash", type: "bytes32", internalType: "bytes32" },
      { indexed: false, name: "issuedAt", type: "uint64", internalType: "uint64" },
    ],
  },
  {
    type: "event",
    name: "CredentialRevoked",
    anonymous: false,
    inputs: [
      { indexed: true, name: "credentialId", type: "uint256", internalType: "uint256" },
      { indexed: true, name: "revoker", type: "address", internalType: "address" },
      { indexed: false, name: "revokedAt", type: "uint64", internalType: "uint64" },
    ],
  },
  {
    type: "event",
    name: "IssuerAdded",
    anonymous: false,
    inputs: [{ indexed: true, name: "issuer", type: "address", internalType: "address" }],
  },
  {
    type: "event",
    name: "IssuerRemoved",
    anonymous: false,
    inputs: [{ indexed: true, name: "issuer", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "addIssuer",
    inputs: [{ name: "issuer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCredential",
    inputs: [{ name: "credentialId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct StudentProjectCredentialRegistry.Credential",
        components: [
          { name: "student", type: "address", internalType: "address" },
          { name: "issuedAt", type: "uint64", internalType: "uint64" },
          { name: "documentHash", type: "bytes32", internalType: "bytes32" },
          { name: "issuer", type: "address", internalType: "address" },
          { name: "revokedAt", type: "uint64", internalType: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIssuer",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issueCredential",
    inputs: [
      { name: "student", type: "address", internalType: "address" },
      { name: "documentHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "credentialId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "nextCredentialId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removeIssuer",
    inputs: [{ name: "issuer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeCredential",
    inputs: [{ name: "credentialId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAdmin",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyCredential",
    inputs: [
      { name: "credentialId", type: "uint256", internalType: "uint256" },
      { name: "suppliedDocumentHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [
      {
        name: "status",
        type: "uint8",
        internalType: "enum StudentProjectCredentialRegistry.VerificationStatus",
      },
      {
        name: "credential",
        type: "tuple",
        internalType: "struct StudentProjectCredentialRegistry.Credential",
        components: [
          { name: "student", type: "address", internalType: "address" },
          { name: "issuedAt", type: "uint64", internalType: "uint64" },
          { name: "documentHash", type: "bytes32", internalType: "bytes32" },
          { name: "issuer", type: "address", internalType: "address" },
          { name: "revokedAt", type: "uint64", internalType: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;
